name: Publish docs to Wiki

on:
  push:
    paths:
      - docs/**
    branches:
      - main

env:
  USER_NAME: ${{ github.actor }}
  USER_EMAIL: ${{ github.actor }}@users.noreply.github.com

jobs:
  publish_docs_to_wiki:
    name: Publish docs to Wiki
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Debug Information
        run: |
          echo "Current directory: $(pwd)"
          echo "Repository: ${{ github.repository }}"
          echo "GITHUB_WORKSPACE: ${{ env.GITHUB_WORKSPACE }}"
          git remote -v

      - name: Pull content from wiki
        run: |
          git config --global user.name "${{ env.USER_NAME }}"
          git config --global user.email "${{ env.USER_EMAIL }}"
          git clone "https://${{ secrets.WIKI_ACTION_TOKEN }}@github.com/${{ github.repository }}.wiki.git" tmp_wiki

      - name: Push content to wiki
        run: |
          rsync -av --delete docs/ tmp_wiki/ --exclude .git
          cd tmp_wiki
          git add .
          git commit -m "Update Wiki content" || echo "No changes to commit"
          git push
        env:
          GIT_TERMINAL_PROMPT: 0